name: Run Azure Login with OpenID Connect
on: [push]

permissions:
      id-token: write
      contents: read
env:
  branch: ${{ github.ref }}
  
jobs: 
  build:
   runs-on: ubuntu-latest
   steps:
   - name: 'build'
     run: mkdir lalala
     
  deploy_prod:
    if: ${{ ${{ github.ref }} == 'main' }}
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: 'Az CLI login'
      uses: azure/login@v1
      with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  
    - name: 'Run Azure CLI commands'
      run: |
          az account show
          az group list
          pwd
          ls -l
          echo $env.branch


  deploy_staging:
    #if: ${{ env.GITHUB_REF == 'staging' }}
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: 'Az CLI login'
      uses: azure/login@v1
      with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  
    - name: 'Run Azure CLI commands'
      run: |
          az account show
          az group list
          pwd
          ls -l
          echo staging
